### PR TITLE
fix(xdl): clean install with android clients

### LINKED ISSUE #1637: expo client:install:android uninstalling but not installing
```
╰─$ expo client:install:android
Could not find your Expo project. If you run this from a project, we can help pick the right Expo client version!
? Do you want to install the latest client? Yes
Uninstalling Expo from Android device.

Done!
╭─~
```

It doesn't actually download the client app or install it. The only way to install it is to run the Android app from dev tools or expo-cli interactive prompt.

cc @byCedric

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #1637

### CODE REVIEW

File: packages/xdl/src/Android.ts [hunk 1]
```diff
@@ -263,7 +263,21 @@ export async function installExpoAsync(url?: string) {
...
+    return '';
+  }
+
+  try {
+    return await getAdbOutputAsync(['uninstall', 'host.exp.exponent']);
+  } catch (e) {
+    Logger.global.error(
+      'Could not uninstall Expo from your device, please uninstall Expo manually and try again.'
+    );
+    throw e;
```
Comment (byCedric) [inline packages/xdl/src/Android.ts]: I put this into the `uninstallExpoAsync` method since this might be used somewhere else. It shows some a generic way that might fix the issue, but that might require some more info. By throwing the error, the execution stops and the error is dumped to the logs.

File: packages/xdl/src/Android.ts [hunk 2]
```diff
@@ -263,7 +263,21 @@ export async function installExpoAsync(url?: string) {
...
+  const isInstalled = await _isExpoInstalledAsync();
+  if (!isInstalled) {
+    return '';
+  }
+
+  try {
+    return await getAdbOutputAsync(['uninstall', 'host.exp.exponent']);
+  } catch (e) {
+    Logger.global.error(
+      'Could not uninstall Expo from your device, please uninstall Expo manually and try again.'
```
Comment (brentvatne) [inline packages/xdl/src/Android.ts]:
```suggestion
      'Could not uninstall Expo client from your device, please uninstall Expo client manually and try again.'
```

File: packages/xdl/src/Android.ts [hunk 3]
```diff
@@ -263,7 +263,21 @@ export async function installExpoAsync(url?: string) {
 
 export async function uninstallExpoAsync() {
   Logger.global.info('Uninstalling Expo from Android device.');
-  return await getAdbOutputAsync(['uninstall', 'host.exp.exponent']);
+
+  // we need to check if its installed, else we might bump into "Failure [DELETE_FAILED_INTERNAL_ERROR]"
+  const isInstalled = await _isExpoInstalledAsync();
+  if (!isInstalled) {
+    return '';
```
Comment (brentvatne) [inline packages/xdl/src/Android.ts]:
```suggestion
    return;
```

File: packages/xdl/src/Android.ts [hunk 4]
```diff
@@ -263,7 +263,21 @@ export async function installExpoAsync(url?: string) {
 
 export async function uninstallExpoAsync() {
```
Comment (brentvatne) [inline packages/xdl/src/Android.ts]:
```suggestion
export async function uninstallExpoAsync(): string | undefined {
```
