### PR TITLE
[config] Created paths module for ios

### LINKED ISSUE #2753: Error when ejecting: the “path” argument must be of type string. Received undefined
I haven't been able to reproduce this but it's being reported in the forums: https://forums.expo.io/t/expo-eject-is-failing-the-path-argument-must-be-of-type-string-received-undefined/43273

If someone can please share a project that reproduces or reliable reproduction steps, this it should be very helpful.

Trace from forums thread:

```
The “path” argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The “path” argument must be of type string. Received undefined
** at validateString (internal/validators.js:120:11)**
** at Object.resolve (path.js:980:7)**
** at new pbxProject (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:35:26)**
** at Object.pbxProject [as project] (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:33:16)**
** at Object.getPbxproj (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/utils/Xcodeproj.ts:164:25)**
** at Object.setDeviceFamily (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/DeviceFamily.ts:52:19)**
** at configureIOSProjectAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/apply/configureIOSProjectAsync.ts:17:26)**
** at configureIOSStepAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:166:3)**
** at Object.ejectAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:81:3)**
** at action (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject.ts:48:5)**
** at Command. (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/exp.ts:302:7)**
```

This seems to be related to `deviceFamily` configuration on iOS.

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

- #2753 seems to be an issue people keep encountering, ~~but we cannot repro it~~.
- fix #2753
- We have a unified paths module for Android already.
- Unify the error messages and warnings.
- Unify the code for resolving project files.

### CODE REVIEW

File: packages/config/src/ios/DeviceFamily.ts [hunk 1]
```diff
@@ -40,7 +33,7 @@ export function getDeviceFamilies(config: ExpoConfig): number[] {
  * @param deviceFamilies
  */
 export function formatDeviceFamilies(deviceFamilies: number[]): string | number {
-  return deviceFamilies.length === 1 ? deviceFamilies[0] : `"${deviceFamilies.join(',')}"`;
+  return `"${deviceFamilies.join(',')}"`;
```
Comment (ide) [inline packages/config/src/ios/DeviceFamily.ts:36]: Change the return type of this function to just `string` so we don't add back the `number` functionality on accident

**Review by brentvatne — APPROVED** [review]
