### PR TITLE
fix(xdl): ping metro bundler when fetching current status

### LINKED ISSUE #1677: Validate that server is actually running in Project.currentStatus and handle cases when it is not
## Description

The [Project.currentStatus(projectDir)](https://github.com/expo/expo-cli/blob/a26baf39c19cefd016eb0acc0445c4a3cba16915/packages/xdl/src/Project.ts#L176-L185) function determines the project status by looking at the packager info in the project `.expo` directory.

Sometimes expo-cli can close in an unexpected way (not exactly sure which steps will repro this, I suspect maybe a hard reboot without closing expo-cli would do it) and the information in `.expo` will be stale. We should validate that the status in this file is actually correct, eg: by sending a request to packager/expo server.  

## Expected Behavior

expo-cli should gracefully handle the information in `.expo` being stale/incorrect.

## Observed Behavior

Cryptic errors like this can happen when running `expo publish`:

```
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Error: connect ECONNREFUSED 127.0.0.1:19001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
```

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #1677

This calls the Metro bundler's `/status` endpoint to determine if the project is running. It's performing a request, so that might slow the method down (with a current max time out of 2 seconds). But it provides a more accurate response about the current status. The code is [copied from `startReactNativeServerAsync`](https://github.com/expo/expo-cli/blob/a26baf39c19cefd016eb0acc0445c4a3cba16915/packages/xdl/src/Project.ts#L1925)

I did not check for the expo server, it [closes itself when you start it](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1985). So that means it restarts every time you run `expo start`, right? And I think both `expo publish` and `expo build` doesn't require the Expo server to run.

Thanks for thinking along @quinlanj 😄

### CODE REVIEW

File: packages/xdl/src/Project.ts [hunk 1]
```diff
@@ -1560,7 +1578,7 @@ export async function buildAsync(
 ): Promise<BuildStatusResult | BuildCreatedResult> {
   /**
     This function corresponds to an apiv1 call and is deprecated.
-    Use 
+    Use
```
Comment (byCedric) [inline packages/xdl/src/Project.ts]: Oh my bad, I think this is my vscode removing trailing whitespaces. I can revert this if you want!

**Comment by brentvatne** [comment]
this seems reasonable! one thing i want to be sure of is that whenever we check the status, if it is bad then we reset it to a clean state.

**Comment by byCedric** [comment]
Sounds good, I wasn't sure if the `currentStatus` was supposed to do this. I'll make it happen asap!

File: packages/xdl/src/Project.ts (hunk 1 above)
Comment (brentvatne) [reply packages/xdl/src/Project.ts]: nbd

**Comment by brentvatne** [comment]
@byCedric - yeah maybe not a good fit for `currentStatus` exactly, maybe make another function that calls `currentStatus` and also takes care of reseting and use that wherever it makes sense

**Comment by fson** [comment]
This pinging of Metro won't be necessary once https://github.com/expo/expo-cli/issues/1434 lands, as it will put Metro into the same process/server as the manifest handler.

The old way to run Metro as a subprocess will still be around for a while to support older SDK versions, so I guess it's still worth it to land this.

**Comment by brentvatne** [comment]
I think it would be very valuable to try to set up an e2e test for this so that when #1434 lands we have an easy way to verify that we don't regress on this. @byCedric - want to give it a try?

File: packages/expo-cli/e2e/__tests__/start-test.ts [hunk 2]
```diff
@@ -27,3 +28,34 @@ test('start --offline', async () => {
...
+  cli.stderr.pipe(process.stderr);
+  cli.stdout.on('data', data => {
+    process.stdout.write(data);
+    if (/Your native app is running/.test(data.toString())) {
+      cli.kill('SIGINT');
+    }
+  });
+
+  try {
+    await promise;
```
Comment (byCedric) [inline packages/expo-cli/e2e/__tests__/start-test.ts]: I had to wait until the command exits with `SIGINT`, else the test would just validate even though it never closes. Not sure if that's just my computer, or if this is also missing from the basic `start --offline` test.

File: packages/expo-cli/e2e/__tests__/start-test.ts [hunk 3]
```diff
@@ -27,3 +28,34 @@ test('start --offline', async () => {
...
+    packagerPort: 19000,
+    packagerPid: 1337,
+  });
+
+  const promise = spawnAsync(EXPO_CLI, ['start', '--offline'], { cwd: projectDir });
+  const cli = promise.child;
+
+  cli.stderr.pipe(process.stderr);
+  cli.stdout.on('data', data => {
+    process.stdout.write(data);
```
Comment (byCedric) [inline packages/expo-cli/e2e/__tests__/start-test.ts]: On my computer, the `on('data')` event is not triggered if chained with `.pipe(process.stdout)`. This achieves the same result without doing additional stuff.

Comment (byCedric) [reply packages/expo-cli/e2e/__tests__/start-test.ts]: Ville helped me out, I'll change the other test as well using `.pipe` after `.on` 😄

File: packages/expo-cli/e2e/__tests__/start-test.ts (hunk 2 above)
Comment (byCedric) [reply packages/expo-cli/e2e/__tests__/start-test.ts]: Talked this over with Ville, we should `await` else Jest will skip the test and not wait for the results.
