### PR TITLE
[expo-cli] Fixed default bare project name for 'expo init'

### LINKED ISSUE #2472: `expo init` gives invalid default name for bare workflow
## Description

When using `expo init`, after selecting any **bare workflow** template, it prompts for project name. I'd like to leave default (`my-app`) but it doesn't pass validation.

That's because default `my-app`:

https://github.com/expo/expo-cli/blob/e7bf70aff0c05ddcbb3d885fd52bc486e03a4830/packages/expo-cli/src/commands/init.ts#L498-L504

Doesn't match regex in:
https://github.com/expo/expo-cli/blob/e7bf70aff0c05ddcbb3d885fd52bc486e03a4830/packages/expo-cli/src/commands/init.ts#L468-L472

I could fix that myself and make a PR, but I'm not sure if I should change regex to match this name or maybe change default name to match regex 🤷

In _managed workflow_, however, default `my-app` is validated properly, because its regex pattern is
https://github.com/expo/expo-cli/blob/e7bf70aff0c05ddcbb3d885fd52bc486e03a4830/packages/expo-cli/src/commands/init.ts#L458

## Expected Behavior

Default name passes the regex pattern

## Observed Behavior

```bash
~/dev/temp » expo init
? Choose a template: expo-template-bare-typescript
? What would you like to name your app? (my-app)
>> Project name can only include ASCII characters A-Z, a-z and 0-9
```

## Environment

`expo-cli@3.24.0`

## Reproducible Demo

`expo init -t bare-minimum` then when prompted for project name, just press Enter to leave default.

### PR DESCRIPTION
**Pull request by barthap**
Fixes #2472 

Changed default name for bare projects to match regex pattern in `expo init`.

### CODE REVIEW

**Review by wkozyra95 — APPROVED** [review]

File: packages/expo-cli/src/commands/init.ts [hunk 1]
```diff
@@ -498,7 +498,7 @@ async function promptForBareConfig(
     ({ projectName } = await prompt({
       name: 'projectName',
       message: 'What would you like to name your app?',
-      default: 'my-app',
+      default: 'MyApp',
```
Comment (EvanBacon) [inline packages/expo-cli/src/commands/init.ts:501]: y tho?

Comment (barthap) [reply packages/expo-cli/src/commands/init.ts:501]: See #2472

**Review by bbarthec — APPROVED** [review]
