### PR TITLE
[config] Fix Android scandir error when ejecting on windows

### LINKED ISSUE #2711: ENOENT: no such file or directory, scandir  when ejecting
## Description

When using expo eject i always get this error: NOENT: no such file or directory, scandir 

## Expected Behavior

expo eject

## Observed Behavior

```
⚠️  iOS config synced with warnings that should be fixed:
- splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen
ENOENT: no such file or directory, scandir 'G:\repos\NewBelled\beLLed\android\app\src\main\java\G:\repos\NewBelled\beLLed\android\app\src\main\java\com\belled'
Error: ENOENT: no such file or directory, scandir 'G:\repos\NewBelled\beLLed\android\app\src\main\java\G:\repos\NewBelled\beLLed\android\app\src\main\java\com\belled'
    at Object.readdirSync (fs.js:955:3)
    at Object.renamePackageOnDisk (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\config\src\android\Package.ts:78:24)
    at configureAndroidProjectAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\apply\configureAndroidProjectAsync.ts:119:31)
    at configureAndroidStepAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject\Eject.ts:218:3)
    at Object.ejectAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject\Eject.ts:82:3)
    at action (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject.ts:48:5)
    at Command.<anonymous> (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:302:7)
```

## Environment

  Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - G:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - G:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.2 => 0.63.2
      react-native-web: ^0.13.14 => 0.13.14
    Expo Workflow: bare

## Reproducible Demo

This is my package.json
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "yarn eslint --ext '.js,.ts,.tsx' src/* --quiet --fix"
  },
  "dependencies": {
    "expo": "^39.0.3",
    "expo-splash-screen": "~0.6.0",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-screens": "^2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "^0.13.14",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.9.1",
    "@react-navigation/material-bottom-tabs": "^5.2.17",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "color": "^3.1.2",
    "react-native-appearance": "^0.3.4",
    "react-native-elements": "^2.3.2",
    "react-native-paper": "^4.2.0",
    "react-native-restart": "^0.0.17",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "^7.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@callstack/eslint-config": "^9.1.0",
    "@types/color": "^3.0.1",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "@typescript-eslint/eslint-plugin": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "^8.3.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.1",
    "jest": "~25.2.6",
    "prettier": "2.1.2",
    "react-test-renderer": "~16.13.1",
    "typescript": "~3.9.2"
  },
  "private": true
}

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #2711

The issue originates (once again) from `glob`. This _always returns_ a posix formatted path, even on Windows. This messes up the `path.sep` because that's different on Windows. I think it's a good thing to normalize paths when using glob, it changes the format of the path to the expected one on Windows.

It's also good to use `path.relative` more when stripping root paths. It takes all differences into account related to windows/posix paths and just returns you the path you need.

### CODE REVIEW

**Comment by byCedric** [comment]
This doesn't fix the issue related to iOS splash screen configuration, I'm looking into that now.

File: packages/config/src/android/Package.ts [hunk 1]
```diff
@@ -25,14 +25,16 @@ function getMainApplicationPath({
...
+  // lets normalize that so we can use it with `.split(path.sep)`
+  return path.normalize(mainApplications[0]);
 }
 
 function getCurrentPackageName(projectRoot: string) {
   const packageRoot = getPackageRoot(projectRoot);
   const mainApplicationPath = getMainApplicationPath({ projectRoot, packageRoot });
   const packagePath = path.dirname(mainApplicationPath);
-  const packagePathParts = packagePath.replace(packageRoot, '').split(path.sep).filter(Boolean);
+  const packagePathParts = path.relative(packageRoot, packagePath).split(path.sep).filter(Boolean);
```
Comment (brentvatne) [inline packages/config/src/android/Package.ts:37]: clever

File: packages/config/src/android/Package.ts [hunk 2]
```diff
@@ -25,14 +25,16 @@ function getMainApplicationPath({
     cwd: packageRoot,
   });
   // If there's more than one, we'll probably have a problem.
-  return mainApplications[0];
+  // Also, glob always returns a posix formatted path (even on windows),
+  // lets normalize that so we can use it with `.split(path.sep)`
+  return path.normalize(mainApplications[0]);
```
Comment (brentvatne) [inline packages/config/src/android/Package.ts:30]: 🔥

Comment (brentvatne) [reply packages/config/src/android/Package.ts:30]: @byCedric - maybe we should make a wrapper around glob that always returns a normalized path to stop this from biting us in the future

**Review by brentvatne — APPROVED** [review]
