### PR TITLE
Fix non-interactive init command

### LINKED ISSUE #332: New snippet prompt doesn't support non-interactive option
## Description
When running: `sudo expo init --non-interactive --template blank --workflow managed Awesome_project`
Snippet prompt appears, change made in pull request #267 prevents the use of `--non-interactive` option.
`--workflow` option was added, but none for the snippet prompt,
making silent install difficult.

## Expected Behavior
Snippet prompt should not appear.
Solution A: Add options to fill snippet prompt as arguments.
Solution B: Skip the snippet prompt when `managed` workflow is selected.

## Observed Behavior

```
? Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration ‣ 50% completed
 {
   "expo": {
     "name": "<The name of your app visible on the home screen>",
     "slug": "Awesome_project"
   }
 }

```

## Environment
```
  Expo CLI 2.7.0 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/bin/node
      npm: 6.5.0 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 2.7.0
```

## Reproducible Demo
`sudo expo init --non-interactive --template blank --workflow managed Awesome_project`

### PR DESCRIPTION
**Pull request by fson**
Allow all options to `init` to be passed as command line flags to enable using `init` in non-interactive mode. Fixes #332 and #342.

**Test plan**

Verified that mandatory arguments are checked in non-interactive mode:
screenshot 2019-02-06 at 21 37 30

Verified that `--ios-bundle-identifier` is validated:
screenshot 2019-02-06 at 21 52 32

Verified that `--android-package` is validated:
screenshot 2019-02-06 at 21 53 28

### CODE REVIEW

File: packages/expo-cli/src/commands/init.js [hunk 1]
```diff
@@ -164,52 +178,108 @@ async function shouldUseYarnAsync() {
...
+      throw new CommandError(
+        'NON_INTERACTIVE',
+        '--name: argument is required in non-interactive mode.'
+      );
+    } else {
+      config.name = options.name;
+    }
+
+    if (workflow === 'advanced') {
+      if (!isString(options.androidPackage) || options.androidPackage === '') {
```
Comment (dsokal) [inline packages/expo-cli/src/commands/init.js]: `options` gathered by commander are always strings unless you explicitly specify a function to convert the value - http://tj.github.io/commander.js/#Command.prototype.option
It doesn't make sense to do `!isString(options.androidPackage) || options.androidPackage === ''` and `!options.androidPackage` is the same check.

Comment (fson) [reply packages/expo-cli/src/commands/init.js]: This is a workaround for a quirk of Commander.js that I run into: if the user runs `expo init hello --non-interactive --android-package` (without a value given to `--android-package`), Commander assumes `--android-package` is a boolean flag and `options.androidPackage` gets set to `true`.

Comment (dsokal) [reply packages/expo-cli/src/commands/init.js]: Fair enough.
