### PR TITLE
Fix/build web status

### LINKED ISSUE #483: Exist status for build web is always 0
## Description

When executing the `build:web` command, it validates if the current project setup is capable of building for web. If it's not, it will provide relevant information to fix it, but the exit status is `0` (ok). This causes CI's to flag builds as successful, even though it wasn't 😄 

## Expected Behavior

Whenever there is a failure building the project for web, I'd expect an error exit code. (Like 1 for example).

## Observed Behavior

```bash
cedric at Cedrics-MacBook-Pro-7 in /Volumes/Drive/Projects/bycedric/actions-expo-test on master ✔
> expo build:web && echo 'project cant be build and should fail'                                     [024cc89]  21:05
Your project is not configured to support web yet!

  package.json
  {
    "dependencies": {
  +      "react-native-web": "^0.11.0",
  +      "react-dom": "^16.7.0"
    },
    "devDependencies": {
  +      "babel-preset-expo": "^5.1.0"
    }
  }

  app.json
  {
    "platforms": [
      "android",
      "ios",
  +      "web"
    ]
  }
project cant be build and should fail
cedric at Cedrics-MacBook-Pro-7 in /Volumes/Drive/Projects/bycedric/actions-expo-test on master ✔
>                                                                                                    [024cc89]  21:06

```

## Environment

```
  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.6.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```

## Reproducible Demo

```bash
$ expo init
$ expo build:web && echo 'should not be visible'
```

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #483 

Feel free to go Gordon Ramsay on my changes 😄 I'm here to help! Here is a short summary of what I changed here.

**What have you done?**

- ~~So first, I was checking where everything was invoked and where the logs came from. After I found this, I slightly adjusted that method (XDL's `Project.bundleWebpackAsync`). I added a "successful-or-not" boolean return when it failed for a reason. To me, that looked like the least significant impact.~~
- ~~After I got this response, I shamelessly copied [this line](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/build/index.js#L101) (using `process.exit`) and add the exit status `1` whenever something goes wrong.~~

- Rethrow any caught exceptions in Project, as [mentioned by Ville](https://github.com/expo/expo-cli/pull/484#discussion_r273120598).
- I [followed Ville's direction closely](https://github.com/expo/expo-cli/pull/484#discussion_r273125291) to create a new error code and throw the xdl error in the Web part.

Hope this helps ❤️

### CODE REVIEW

**Comment by cruzach** [comment]
This looks great @byCedric , nice catch!

I'm going to let someone with more experience with the `expo-cli` codebase also take a look, but it looks good to me 👍

File: packages/xdl/src/Project.js [hunk 1]
```diff
@@ -1885,7 +1885,7 @@ export async function bundleWebpackAsync(projectRoot, packagerOpts) {
   const hasWebSupport = await Web.hasWebSupportAsync(projectRoot);
   if (!hasWebSupport) {
     Web.logWebSetup();
-    return;
+    return false;
```
Comment (fson) [inline packages/xdl/src/Project.js]: Let's throw an error here as well. I think the best way to do this would be to add a new function `Web.ensureWebSupportAsync(projectRoot)`, which checks `hasWebSupportAsync` and throws an error like `new XDLError(ErrorCode.WEB_NOT_CONFIGURED, getWebSetupLogs())`.

File: packages/xdl/src/Project.js [hunk 2]
```diff
@@ -1920,7 +1920,10 @@ export async function bundleWebpackAsync(projectRoot, packagerOpts) {
       'expo',
       'There was a problem building your web project. ' + message
     );
+    return false;
```
[the remark this answers is not in the document]
Comment (byCedric) [reply packages/xdl/src/Project.js]: Sure, sounds reasonable! You want to remove the `boolean` success response and just rethrow the error right? If so, what error would be thrown when the project is not ready for web builds? (The start of this same method)

File: packages/xdl/src/Project.js (hunk 1 above)
Comment (byCedric) [reply packages/xdl/src/Project.js]: Will do this in the evening (CEST)!

**Comment by byCedric** [comment]
Done! I hope I got it right, I followed your directions closely @fson 😄Thanks for taking a look and the help! ❤️(PS. Was nice meeting both of you in Poland 😄)

File: packages/xdl/src/Project.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (byCedric) [reply packages/xdl/src/Project.js]: Done

File: packages/xdl/src/Project.js (hunk 1 above)
Comment (byCedric) [reply packages/xdl/src/Project.js]: Done

**Comment by fson** [comment]
Looks great. Thanks again @byCedric!

**Comment by byCedric** [comment]
My pleasure!
