### PR TITLE
[cli] Fail upgrade when expo install throws

### LINKED ISSUE #2114: expo upgrade doesn't know when expo package upgrade failed
## Description

When running `expo upgrade` on existing project, if there's a problem when upgrading `expo` package, expo-cli still believes that everything went well which results in broken upgrade.

## Expected Behavior

If upgrading `expo` package fails, expo-cli should stop whatever it's doing

## Observed Behavior

```
✖ Failed to install expo package with error: yarnpkg exited with non-zero code: 1
✔ Installed expo@^37.0.0
```

Manually upgrading expo reveals the error as:

```
error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.15.1"
```

## Environment

expo-cli 3.20.3
upgrading from SDK 35 to SDK 37

## Reproducible Demo

Try upgrading with `expo upgrade` while running on node version older than `10.17` (hard to create a reproducible demo for this)

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #2114

### CODE REVIEW

File: packages/expo-cli/src/commands/upgrade.ts [hunk 1]
```diff
@@ -451,6 +451,7 @@ export async function upgradeAsync(
     await packageManager.addAsync(expoPackageToInstall);
   } catch (e) {
     installingPackageStep.fail(`Failed to install expo package with error: ${e.message}`);
+    throw e;
   } finally {
```
Comment (brentvatne) [inline packages/expo-cli/src/commands/upgrade.ts:455]:
```suggestion
```

File: packages/expo-cli/src/commands/upgrade.ts [hunk 2]
```diff
@@ -451,6 +451,7 @@ export async function upgradeAsync(
...
     installingPackageStep.succeed(`Installed ${expoPackageToInstall}`);
   }
```
Comment (brentvatne) [inline packages/expo-cli/src/commands/upgrade.ts:457]:
```suggestion
```

File: packages/expo-cli/src/commands/upgrade.ts [hunk 3]
```diff
@@ -451,6 +451,7 @@ export async function upgradeAsync(
     await packageManager.addAsync(expoPackageToInstall);
   } catch (e) {
     installingPackageStep.fail(`Failed to install expo package with error: ${e.message}`);
+    throw e;
   } finally {
     installingPackageStep.succeed(`Installed ${expoPackageToInstall}`);
```
Comment (brentvatne) [inline packages/expo-cli/src/commands/upgrade.ts:456]:
```suggestion
  installingPackageStep.succeed(`Installed ${expoPackageToInstall}`);
```

File: packages/expo-cli/src/commands/upgrade.ts [hunk 4]
```diff
@@ -451,9 +451,8 @@ export async function upgradeAsync(
     await packageManager.addAsync(expoPackageToInstall);
   } catch (e) {
     installingPackageStep.fail(`Failed to install expo package with error: ${e.message}`);
-  } finally {
-    installingPackageStep.succeed(`Installed ${expoPackageToInstall}`);
-  }
+    throw e;
```
Comment (brentvatne) [inline packages/expo-cli/src/commands/upgrade.ts:454]:
```suggestion
    throw e;
  }
```
