### PR TITLE
[expo-cli] don't allow to use png icon with alpha channel

### LINKED ISSUE #374: expo build:ios - IPA - transparent App Store Icon
## Description
`iOS` rejects uploading generated `IPA` when `App Store Icon` is transparent

## Expected Behavior

`expo build:ios` during project checking phase would warn about transparency of asset that would be used as `App Store Icon`.

## Observed Behavior

No such checking is provided and user is presented with error at the final stage of app uploading.

## Environment

`iOS` build submission for TestFlight

## Reproducible Demo

- build app using `expo build:ios`
- try to publihs in using `Appliaction Loader`
- observe error presented in the attached screenshot at the final stage of publishing process

screenshot 2019-02-13 at 11 26 18

### PR DESCRIPTION
**Pull request by dsokal**
Closes #374

### CODE REVIEW

File: packages/expo-cli/src/commands/build/ios/IOSBuilder.js [hunk 1]
```diff
@@ -158,6 +161,30 @@ See https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#
...
+        throw new XDLError(
+          ErrorCode.INVALID_ASSETS,
+          `Your application icon (${icon}) can't have an alpha channel if you wish to upload your app to Apple Store.`
+        );
+      }
+    } catch (err) {
+      if (err instanceof XDLError) {
+        throw err;
+      } else {
+        // something weird happened, let's assume the icon is correct
```
Comment (osdnk) [inline packages/expo-cli/src/commands/build/ios/IOSBuilder.js]: XD
