### PR TITLE
[expo-cli] fix icon validation

### LINKED ISSUE #414: Version 2.11.7 fail on alpha channel in Icon
After upgrading from version 2.11.6 to 2.11.7, expo build:ios fails with:
"can't have an alpha channel if you wish to upload your app to Apple Store."

this is on an application that was already uploaded with the same icon, so the issue isnt in the specific icon. Revert to version 2.11.6 allowed the build to complete and the upload to app store to be completed.

The icon path in the app.json is:
"icon": "./assets/images/icon.png"

### PR DESCRIPTION
**Pull request by dsokal**
Closes #414 

In order to verify whether a png doesn't have any transparency, we not only need to check whether the png doesn't have an alpha channel, but we also have to check every pixel and see if the value for the alpha channel is equal to 255.

### CODE REVIEW

File: packages/expo-cli/src/commands/build/ios/utils/image.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+import { XDLError, ErrorCode } from 'xdl';
+
+export async function ensurePNGIsNotTransparent(imagePath) {
+  let hasAlreadyResolved = false;
+  return new Promise((res, rej) => {
+    fs.createReadStream(imagePath)
+      .pipe(new PNG({ filterType: 4 }))
+      .on('metadata', ({ colorType }) => {
+        if (colorType !== 6) {
+          hasAlreadyResolved = true;
```
Comment (fson) [inline packages/expo-cli/src/commands/build/ios/utils/image.js]: Should the read stream be destroyed at this point to prevent unnecessarily reading rest of the file?

File: packages/expo-cli/src/commands/build/ios/utils/image.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+          res();
+        }
+      })
+      .on('parsed', function() {
+        if (hasAlreadyResolved) {
+          return;
+        }
+        for (let y = 0; y < this.height; y++) {
+          for (let x = 0; x < this.width; x++) {
+            let idx = (this.width * y + x) << 2;
```
Comment (fson) [inline packages/expo-cli/src/commands/build/ios/utils/image.js]:
```suggestion
            let idx = (this.width * y + x) * 4;
```

**Comment by dsokal** [comment]
Hey @fson, 
thanks for your feedback. Does it look good to you now?

**Comment by evanheckert** [comment]
Hoping this allows us to build our ios app. Reworked icon PNGs every way possible, but builds fail every time. Any other workaround while we wait for the next version of expo-cli?

**Comment by hadnazzar** [comment]
@dsokal Hello,  i updated my expo-cli to 2.14.0 but i am still getting error with
`
 expo build:ios
`


`Your application icon can't have transparency if you wish to upload your app to Apple Store.`

**Comment by dsokal** [comment]
@hadnazzar so maybe your application icon has an alpha channel? It should work properly in the latest version.

**Comment by hadnazzar** [comment]
@dsokal yes i created that icon with older version of expo-cli that could be the reason. 
Thank you!

**Comment by evanheckert** [comment]
@hadnazzar I have a 1024 x 1024 .png with no transparency, and my build still fails when 'resizing':

https://expo.io/builds/6abf85ac-c685-4372-a92c-9b77fa88a6ef

**Comment by hadnazzar** [comment]
@evanheckert are you using default image in `/assets/images/icon.png` ?

**Comment by dsokal** [comment]
@evanheckert the issue you're experiencing is a different one. It's not related to the transparency of the icon. It's a common issue when people upgrade Expo SDK version and they don't add the `assetBundlePatterns` key to `app.json` file. Please read the documentation.
