### PR TITLE
[expo-env-info] don't show workflow type outside of project folder

### LINKED ISSUE #4264: [npx-env-info] always shows Expo workflow, even when not inside a project folder
### Summary

image

### Environment

See above, happens on all platforms.

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

_No response_

### Reproducible demo or steps to reproduce from a blank project

- Run `npx expo-env-info`

### PR DESCRIPTION
**Pull request by kbrandwijk**
# Why

Closes #4264 

# How

# Test Plan

### CODE REVIEW

File: packages/expo-env-info/src/diagnosticsAsync.ts [hunk 1]
```diff
@@ -34,7 +35,20 @@ function getEnvironmentInfoAsync(): Promise<string> {
   );
 }
 
-export async function isBareWorkflowProject(projectRoot: string): Promise<boolean> {
+/* Poor mans implementation to prevent bloating the package size */
+async function isInsideProjectAsync(projectRoot: string): Promise<boolean> {
```
Comment (EvanBacon) [inline packages/expo-env-info/src/diagnosticsAsync.ts:39]: Test this function

**Review by EvanBacon — DISMISSED** [review]
Needs tests
