### PR TITLE
[config-plugins] Fix app gradle versionName replacement after ejecting twice

### LINKED ISSUE #3081: Ejecting twice doesnt update app build version name
## Description

Ejecting multiple times with `expo eject` doesn't sync the `android/app/build.gradle`'s `versionName`.

## Environment

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
      npm: 7.0.11 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

## Expected Behavior

When I eject multiple times, I expect both `versionCode` and `versionName` to be updated in `android/app/build.gradle`.

## Observed Behavior

- `versionCode` is updated properly
- `versionName` is _not_ updated when it's not the default `"1.0"` value.

## Reproducible Demo

- `$ npx create-react-native-app`
- Update `app.json`'s `expo.version` to `2.0.0`
- `$ expo eject`
- Validate if `android/app/build.gradle` `versionName` is set to `2.0.0`
- Update `app.json`'s `expo.version` to `3.0.0`
- `$ expo eject`
- `android/app/build.gradle` `versionName` is still set to `2.0.0`

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #3081

The issue was that the `versionToReplace` parameter was never provided. There also didn't seem to be a good way of retrieving the value set in `android/app/build.gradle`.

Instead of doing that, I applied the same approach as [this `versionCode` fix](https://github.com/expo/expo-cli/commit/edd590b825db32b2db3dd8f0af324b7b3db24d6c#diff-791f73eecd02a99877dd27c2ea8f8eba5ee22d21ea2cda0c0622bf322b6d6b8fL47-L59)

### CODE REVIEW

File: packages/config-plugins/src/android/Version.ts [hunk 1]
```diff
@@ -25,17 +23,13 @@ export function getVersionName(config: Pick<ExpoConfig, 'version'>) {
...
-  versionToReplace = DEFAULT_VERSION_NAME
-) {
+export function setVersionName(config: Pick<ExpoConfig, 'version'>, buildGradle: string) {
   const versionName = getVersionName(config);
   if (versionName === null) {
     return buildGradle;
   }
 
-  const pattern = new RegExp(`versionName "${versionToReplace}"`);
+  const pattern = new RegExp(`versionName.*`);
```
Comment (EvanBacon) [inline packages/config-plugins/src/android/Version.ts:32]:
```suggestion
  const pattern = new RegExp(`versionName ".*"`);
```
