### PR TITLE
[expo-cli] add warning when no configuration found and exit process

### LINKED ISSUE #218: Extraneous error message when app.json is missing
I noticed this when starting a project in the wrong directory:

```
[10:48:41] Starting project at /Users/brentvatne/coding/react-navigation-core
[10:48:42] Expo DevTools is running at http://localhost:19002
[10:48:42] Error: Missing app.json. See https://docs.expo.io/
[10:48:42] Cannot read property 'isDetached' of null
[10:48:42] Set EXPO_DEBUG=true in your env to view the stack trace.
```

See that `Cannot read property 'isDetached' of null` shows up after the `Missing app.json` message.

As an aside, it may be useful to suggest that this is potentially not an Expo project directory given the lack of app.json.

### PR DESCRIPTION
**Pull request by jakubste**
Fixes #218 
zrzut ekranu 2018-11-28 o 12 17 36

### CODE REVIEW

File: packages/expo-cli/src/commands/start.js [hunk 1]
```diff
@@ -37,6 +37,11 @@ async function action(projectDir, options) {
   const nonInteractive = options.parent && options.parent.nonInteractive;
   const { exp } = await ProjectUtils.readConfigJsonAsync(projectDir);
 
+  if (exp == null) {
+    log.warn('No Expo configuration found. Are you sure this is a project directory?');
+    process.exit();
```
Comment (dsokal) [inline packages/expo-cli/src/commands/start.js]:
```suggestion
    process.exit(1);
```

File: packages/expo-cli/src/commands/start.js [hunk 2]
```diff
@@ -37,6 +37,11 @@ async function action(projectDir, options) {
   const nonInteractive = options.parent && options.parent.nonInteractive;
   const { exp } = await ProjectUtils.readConfigJsonAsync(projectDir);
 
+  if (exp == null) {
```
Comment (dsokal) [inline packages/expo-cli/src/commands/start.js]: I hope `==` is intentional choice :P
