### PR TITLE
[xdl] fix extraFields in logger

### LINKED ISSUE #779: buildPhaseLogger error
## Description

When I attempt to publish using the CLI I'm getting this error message. 

```
Building JavaScript bundle [] 100%[01:49:26] Finished building JavaScript bundle in 296ms.
[01:49:26] Uploading JavaScript bundles
[01:49:28] buildPhaseLogger.info is not a function
[01:49:28] TypeError: buildPhaseLogger.info is not a function
    at Object.getManifestAsync (/@expo/xdl@55.0.10/src/detach/ExponentTools.ts:91:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Exited with code 1
```

## Expected Behavior

I'd expect the publish to complete successfully. It got to 100%, then got an error

## Environment

The environment is CircleCI's circleci/node:10.15 docker container

I was able to find that others are having the same issue. 
https://forums.expo.io/t/expo-cli-2-20-10-publish-error/24416

### PR DESCRIPTION
**Pull request by wkozyra95**
Fixes #779

### CODE REVIEW

File: packages/xdl/src/detach/Logger.ts [hunk 1]
```diff
@@ -25,7 +25,9 @@ export class Logger {
   }
 
   withFields(extraFields: any) {
-    return Object.assign({}, this, { extraFields: { ...this.extraFields, ...extraFields } });
+    const logger = new Logger()
```
Comment (dsokal) [inline packages/xdl/src/detach/Logger.ts]:
```suggestion
    const logger = new Logger();
```
